"""empty message

Revision ID: 69f609d99e55
Revises: e5a842bfaa6c
Create Date: 2020-09-30 08:52:24.522734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f609d99e55'
down_revision = 'e5a842bfaa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_dni',
    sa.Column('tipo_dni_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=80), nullable=False),
    sa.Column('ts_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('tipo_dni_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_dni')
    # ### end Alembic commands ###
