"""empty message

Revision ID: bee4527759b3
Revises: 
Create Date: 2020-09-30 08:20:01.827694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee4527759b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provincia',
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=80), nullable=False),
    sa.Column('ts_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('provincia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provincia')
    # ### end Alembic commands ###
